# Generated by Django 6.0 on 2026-03-22 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('communicates_with', models.ManyToManyField(blank=True, to='api.component')),
            ],
        ),
        migrations.CreateModel(
            name='AttackStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fr_et', models.CharField(max_length=100)),
                ('fr_se', models.CharField(max_length=100)),
                ('fr_koC', models.CharField(max_length=100)),
                ('fr_WoO', models.CharField(max_length=100)),
                ('fr_eq', models.CharField(max_length=100)),
                ('prepared_by', models.ManyToManyField(blank=True, to='api.attackstep')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_steps', to='api.component')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fr_et', models.CharField(max_length=100)),
                ('fr_se', models.CharField(max_length=100)),
                ('fr_koC', models.CharField(max_length=100)),
                ('fr_WoO', models.CharField(max_length=100)),
                ('fr_eq', models.CharField(max_length=100)),
                ('attack_steps', models.ManyToManyField(blank=True, to='api.attackstep')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='api.component')),
            ],
        ),
        migrations.AddField(
            model_name='attackstep',
            name='controls',
            field=models.ManyToManyField(blank=True, to='api.control'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DamageScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('affected_CIA_parts', models.CharField(blank=True, max_length=100)),
                ('impact_scale', models.CharField(max_length=50)),
                ('safety_impact', models.CharField(max_length=100)),
                ('finantial_impact', models.CharField(max_length=100)),
                ('operational_impact', models.CharField(max_length=100)),
                ('privacy_impact', models.CharField(max_length=100)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_scenarios', to='api.component')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage_scenarios', to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='api.project'),
        ),
        migrations.AddField(
            model_name='component',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='api.project'),
        ),
        migrations.AddField(
            model_name='attackstep',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack_steps', to='api.project'),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='DataEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_entities', to='api.component')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_entities', to='api.project')),
                ('technology', models.ManyToManyField(blank=True, to='api.technology')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='technology',
            field=models.ManyToManyField(blank=True, to='api.technology'),
        ),
        migrations.CreateModel(
            name='ThreatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_classes', to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='attackstep',
            name='threat_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.threatclass'),
        ),
        migrations.CreateModel(
            name='ThreatScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attack_step', models.ManyToManyField(blank=True, to='api.attackstep')),
                ('damage_scenario', models.ManyToManyField(blank=True, to='api.damagescenario')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_scenarios', to='api.project')),
                ('threat_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.threatclass')),
            ],
        ),
        migrations.AddField(
            model_name='damagescenario',
            name='threat_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.threatscenario'),
        ),
        migrations.CreateModel(
            name='Comporomises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compromised_CIA_part', models.CharField(max_length=100)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromises', to='api.component')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compromises', to='api.project')),
                ('threat_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromise_items', to='api.threatscenario')),
            ],
        ),
        migrations.AddField(
            model_name='attackstep',
            name='threat_scenario',
            field=models.ManyToManyField(blank=True, to='api.threatscenario'),
        ),
    ]
