# Generated by Django 6.0 on 2026-01-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ThreatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('communicates_with', models.ManyToManyField(blank=True, to='api.component')),
                ('technology', models.ManyToManyField(to='api.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('fr_et', models.CharField()),
                ('fr_se', models.CharField()),
                ('fr_koC', models.CharField()),
                ('fr_WoO', models.CharField()),
                ('fr_eq', models.CharField()),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.component')),
            ],
        ),
        migrations.CreateModel(
            name='DataEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.component')),
                ('technology', models.ManyToManyField(to='api.technology')),
            ],
        ),
        migrations.CreateModel(
            name='AttackStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('fr_et', models.CharField()),
                ('fr_se', models.CharField()),
                ('fr_koC', models.CharField()),
                ('fr_WoO', models.CharField()),
                ('fr_eq', models.CharField()),
                ('prepared_by', models.ManyToManyField(blank=True, to='api.attackstep')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.component')),
                ('control', models.ManyToManyField(to='api.control')),
                ('threat_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.threatclass')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('attackStep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.attackstep')),
                ('threat_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.threatclass')),
            ],
        ),
        migrations.CreateModel(
            name='DamageScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('affected_CIA_parts', models.JSONField()),
                ('impact_scale', models.CharField()),
                ('safety_impact', models.CharField()),
                ('finantial_impact', models.CharField()),
                ('operational_impact', models.CharField()),
                ('privacy_impact', models.CharField()),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.component')),
                ('threat_scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.threatscenario')),
            ],
        ),
        migrations.CreateModel(
            name='Comporomises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compromised_CIA_part', models.CharField()),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.component')),
                ('threat_scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.threatscenario')),
            ],
        ),
    ]
