# Generated by Django 6.0 on 2026-01-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_technology_threatclass_component_control_dataentity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='communicates_with',
            field=models.ManyToManyField(blank=True, null=True, to='api.component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='technology',
            field=models.ManyToManyField(null=True, to='api.technology'),
        ),
    ]
