# Generated by Django 6.0 on 2026-01-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_component_communicates_with_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='technology',
        ),
    ]
