# Generated by Django 6.0 on 2026-01-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_component_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='communicates_with',
            field=models.ManyToManyField(blank=True, to='api.component'),
        ),
    ]
