# Generated by Django 6.0 on 2026-01-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_component_communicates_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='technology',
            field=models.ManyToManyField(blank=True, to='api.technology'),
        ),
    ]
