# Generated by Django 5.1.7 on 2026-04-24 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_compromise_cia_bitmask"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Node",
        ),
        migrations.AddField(
            model_name="attackstep",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="attackstep",
            name="required_access",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="control",
            name="control_type",
            field=models.CharField(
                choices=[
                    ("preventive", "Preventive"),
                    ("detective", "Detective"),
                    ("corrective", "Corrective"),
                    ("compensating", "Compensating"),
                ],
                default="preventive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="control",
            name="status",
            field=models.CharField(
                choices=[
                    ("identified", "Identified"),
                    ("planned", "Planned"),
                    ("implemented", "Implemented"),
                    ("retired", "Retired"),
                ],
                default="identified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_verified", "Not verified"),
                    ("in_review", "In review"),
                    ("verified", "Verified"),
                    ("failed", "Failed"),
                ],
                default="not_verified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="damagescenario",
            name="affected_business",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagescenario",
            name="affected_road_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="damagescenario",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="damagescenario",
            name="impact_rationale",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="threatscenario",
            name="attack_vector",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="threatscenario",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="threatscenario",
            name="entry_point",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="threatscenario",
            name="preconditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="threatscenario",
            name="target_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_threat_scenarios",
                to="api.component",
            ),
        ),
        migrations.AddField(
            model_name="threatscenario",
            name="target_data_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_threat_scenarios",
                to="api.dataentity",
            ),
        ),
    ]
