# Generated by Django 5.1.7 on 2026-04-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_delete_node_attackstep_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attackstep",
            old_name="prepared_by",
            new_name="previous_steps",
        ),
        migrations.AlterField(
            model_name="attackstep",
            name="previous_steps",
            field=models.ManyToManyField(
                blank=True,
                related_name="next_steps",
                symmetrical=False,
                to="api.attackstep",
            ),
        ),
        migrations.RemoveField(
            model_name="control",
            name="control_type",
        ),
        migrations.RemoveField(
            model_name="control",
            name="status",
        ),
        migrations.RemoveField(
            model_name="control",
            name="verification_status",
        ),
        migrations.RemoveField(
            model_name="damagescenario",
            name="affected_business",
        ),
        migrations.RemoveField(
            model_name="damagescenario",
            name="affected_road_users",
        ),
        migrations.RemoveField(
            model_name="damagescenario",
            name="impact_rationale",
        ),
        migrations.RemoveField(
            model_name="threatscenario",
            name="attack_vector",
        ),
        migrations.RemoveField(
            model_name="threatscenario",
            name="entry_point",
        ),
        migrations.RemoveField(
            model_name="threatscenario",
            name="preconditions",
        ),
        migrations.RemoveField(
            model_name="threatscenario",
            name="target_component",
        ),
        migrations.RemoveField(
            model_name="threatscenario",
            name="target_data_entity",
        ),
    ]
