# Generated by Django 6.0 on 2026-01-03 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_component_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagescenario',
            name='affected_CIA_parts',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='damagescenario',
            name='threat_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.threatscenario'),
        ),
    ]
