# Generated by Django 5.1.7 on 2026-04-26 00:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_threatscenario_components_remove_damage_component"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamageScenarioConcern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "affected_CIA_parts",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_scenario_concerns",
                        to="api.component",
                    ),
                ),
                (
                    "damage_scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concerns",
                        to="api.damagescenario",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("damage_scenario", "component"),
                        name="unique_damage_scenario_component_concern",
                    )
                ],
            },
        ),
    ]
