# Generated by Django 6.0.4 on 2026-04-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_damagescenarioconcern'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='threat_scenarios',
            field=models.ManyToManyField(blank=True, related_name='controls', to='api.threatscenario'),
        ),
    ]
