# Generated by Django 6.0.4 on 2026-04-26 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_control_threat_scenarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fr_et', models.PositiveSmallIntegerField(choices=[(0, '<=1 day'), (1, '<=1 week'), (4, '<=1 month'), (10, '<=3 months'), (17, '<=6 months'), (19, '>6 months'), (99, 'Not practical')], default=0)),
                ('fr_se', models.PositiveSmallIntegerField(choices=[(0, 'Layman'), (3, 'Proficient'), (6, 'Expert'), (8, 'Multiple experts')], default=0)),
                ('fr_koC', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (3, 'Restricted'), (7, 'Sensitive'), (11, 'Critical')], default=0)),
                ('fr_WoO', models.PositiveSmallIntegerField(choices=[(0, 'Unnecessary/unlimited'), (1, 'Easy'), (4, 'Moderate'), (10, 'Difficult'), (99, 'None')], default=0)),
                ('fr_eq', models.PositiveSmallIntegerField(choices=[(0, 'Standard'), (4, 'Specialized'), (7, 'Bespoke'), (9, 'Multiple bespoke')], default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='control',
            name='control_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='api.controlclass'),
        ),
    ]
