# Generated by Django 6.0.4 on 2026-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_control_attackstep_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attackstep',
            name='controls',
        ),
        migrations.AlterField(
            model_name='control',
            name='attack_steps',
            field=models.ManyToManyField(blank=True, related_name='controls', to='api.attackstep'),
        ),
    ]
