# Generated by Django 6.0.4 on 2026-04-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_attackstep_controls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controls', models.ManyToManyField(blank=True, related_name='control_groups', to='api.control')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_groups', to='api.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
