# Generated by Django 6.0.4 on 2026-05-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cybersecuritygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackstep',
            name='mitre_technique_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='attackstep',
            name='mitre_technique_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
