# Generated by Django 6.0.4 on 2026-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_attackstep_mitre_technique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatclass',
            name='mitre_tactic_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='threatclass',
            name='mitre_tactic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
